import { PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import crypto from 'node:crypto';
import { s3Client, S3_BUCKET, S3_PREFIX } from '../../config/s3.js';
import { ApiError } from '../utils/ApiError.js';
import { PendingUpload } from '../../modules/files/pendingUpload.model.js';

/**
 * S3 Service — Presigned URL generation
 *
 * All file operations use presigned URLs so that files never pass through the backend.
 * The client uploads/downloads directly to/from S3 using time-limited URLs.
 *
 * Operations fail at runtime if AWS credentials or bucket are not configured.
 */
export class S3Service {
  private static instance: S3Service;

  static getInstance(): S3Service {
    if (!S3Service.instance) {
      S3Service.instance = new S3Service();
    }
    return S3Service.instance;
  }

  private ensureConfigured(): void {
    if (!s3Client) {
      throw ApiError.internal('S3 client not configured. Set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in environment.');
    }
    if (!S3_BUCKET) {
      throw ApiError.internal('S3 bucket not configured. Set AWS_S3_BUCKET in environment.');
    }
  }

  /**
   * Generate a presigned PUT URL for direct client upload to S3.
   *
   * @param fileName - Original file name (used in the key for traceability)
   * @param mimeType - MIME type of the file (enforced by S3)
   * @param module - Module name (records, prescriptions, invoices, etc.)
   * @param expirySeconds - URL expiry in seconds (default: 3600 = 1 hour)
   * @returns The presigned upload URL and the generated fileKey
   */
  async generateUploadUrl(
    fileName: string,
    mimeType: string,
    module: string,
    expirySeconds = 3600,
  ): Promise<{ uploadUrl: string; fileKey: string }> {
    this.ensureConfigured();

    const uuid = crypto.randomUUID();
    const fileKey = `${S3_PREFIX}${module}/${uuid}_${fileName}`;

    const command = new PutObjectCommand({
      Bucket: S3_BUCKET,
      Key: fileKey,
      ContentType: mimeType,
    });

    try {
      const uploadUrl = await getSignedUrl(s3Client!, command, { expiresIn: expirySeconds });
      return { uploadUrl, fileKey };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown S3 error';
      throw ApiError.internal(`Failed to generate upload URL: ${message}`);
    }
  }

  /**
   * Generate a presigned GET URL for direct client download from S3.
   *
   * @param fileKey - The S3 object key (e.g. hospital-management/records/uuid_filename.pdf)
   * @param expirySeconds - URL expiry in seconds (default: 300 = 5 minutes)
   * @returns The presigned download URL
   */
  async generateDownloadUrl(fileKey: string, expirySeconds = 300): Promise<string> {
    this.ensureConfigured();

    const command = new GetObjectCommand({
      Bucket: S3_BUCKET,
      Key: fileKey,
    });

    try {
      return await getSignedUrl(s3Client!, command, { expiresIn: expirySeconds });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown S3 error';
      throw ApiError.internal(`Failed to generate download URL: ${message}`);
    }
  }

  /**
   * Batch generate presigned GET URLs for multiple files.
   *
   * @param fileKeys - Array of S3 object keys
   * @param expirySeconds - URL expiry in seconds (default: 300)
   * @returns A map of fileKey → downloadUrl (empty string for failed keys)
   */
  async generateDownloadUrls(
    fileKeys: string[],
    expirySeconds = 300,
  ): Promise<Record<string, string>> {
    this.ensureConfigured();

    const urls: Record<string, string> = {};

    for (const fileKey of fileKeys) {
      try {
        urls[fileKey] = await this.generateDownloadUrl(fileKey, expirySeconds);
      } catch {
        urls[fileKey] = '';
      }
    }

    return urls;
  }

  /**
   * Delete a file from S3.
   *
   * @param fileKey - The S3 object key to delete
   */
  async deleteFile(fileKey: string): Promise<void> {
    this.ensureConfigured();

    const command = new DeleteObjectCommand({
      Bucket: S3_BUCKET,
      Key: fileKey,
    });

    try {
      await s3Client!.send(command);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown S3 error';
      throw ApiError.internal(`Failed to delete file: ${message}`);
    }
  }

  /**
   * Verify and consume a pending upload.
   *
   * Checks that a fileKey was generated by the requesting user and has not expired.
   * Marks the pending upload as consumed so it cannot be reused.
   *
   * @param userId - The ID of the user who requested the upload
   * @param fileKey - The S3 object key to verify
   */
  async verifyAndConsume(userId: string, fileKey: string): Promise<void> {
    this.ensureConfigured();

    const pendingUpload = await PendingUpload.findOne({
      fileKey,
      userId,
      consumed: false,
    });

    if (!pendingUpload) {
      throw ApiError.forbidden('Invalid or unauthorized file key');
    }

    if (pendingUpload.expiresAt < new Date()) {
      throw ApiError.badRequest('Upload session has expired');
    }

    pendingUpload.consumed = true;
    await pendingUpload.save();
  }

  /**
   * Upload a buffer directly to S3 (for server-generated content like PDFs).
   *
   * @param fileKey - The S3 object key
   * @param buffer - The file content as a Buffer
   * @param mimeType - MIME type of the content
   */
  async uploadBuffer(fileKey: string, buffer: Buffer, mimeType = 'application/octet-stream'): Promise<void> {
    this.ensureConfigured();

    const command = new PutObjectCommand({
      Bucket: S3_BUCKET,
      Key: fileKey,
      Body: buffer,
      ContentType: mimeType,
    });

    try {
      await s3Client!.send(command);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown S3 error';
      throw ApiError.internal(`Failed to upload file: ${message}`);
    }
  }
}

export const s3Service = S3Service.getInstance();
